version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onflytrips_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy 
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: onflytrips
      DB_USERNAME: root
      DB_PASSWORD: root
    command: >
      sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: onflytrips_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: onflytrips
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: onflytrips_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  dbdata:
